name: Deployment workflow

on:
  push:
    branches:
      - deployment

env:
  NODE_ENV: test
  PORT: ${{ secrets.PORT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

jobs:
  lint_and_test:
    name: 'Lint and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 'Lint & test'
        run: |
          npm install --prefix ./packages/backend
          npm run lint --prefix ./packages/backend && npm run test --prefix ./packages/backend
          npm install --prefix ./packages/frontend
          npm run lint --prefix ./packages/frontend

  check_changes:
    name: 'Check for changes'
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.changes.outputs.backend }}
      frontend_changed: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Check for changes'
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - packages/frontend/**
            backend:
              - packages/backend/**

  build_backend:
    if: ${{ needs.check_changes.outputs.backend_changed == 'true' }}
    name: 'Build backend'
    runs-on: ubuntu-latest
    needs: [lint_and_test, check_changes]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 'Build backend'
        run: |
          npm install --prefix ./packages/backend
          ./packages/backend/build.sh
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ./dist.zip

  build_frontend:
    if: ${{ needs.check_changes.outputs.frontend_changed == 'true' }}
    name: 'Build frontend'
    runs-on: ubuntu-latest
    needs: [lint_and_test, check_changes]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build frontend
        run: |
          npm install --prefix ./packages/frontend
          npm run build --prefix ./packages/frontend
          mv ./packages/frontend/dist ./
          zip -r ./dist.zip dist
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ./dist.zip

  deploy_backend:
    if: ${{ needs.check_changes.outputs.backend_changed == 'true' }}
    name: Deploy backend
    runs-on: ubuntu-latest
    needs: [build_backend, check_changes]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend
      - name: Deploy
        run: |
          ls -la
          echo "Deploy backend"
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend
      - name: Unzip artifact
        run: unzip dist.zip && mv dist/* . && rm -rf dist

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'postbuddy-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C7190BF5B21E4CFBBE09A130C724085D }}
          package: .

  deploy_frontend:
    if: ${{ needs.check_changes.outputs.frontend_changed == 'true' }}
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: [build_frontend, check_changes]
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
      - name: Unzip artifact
        run: unzip dist.zip && mv dist/* . && rm -rf dist
      - name: Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: /
          output_location: .
