name: Pull request workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  NODE_ENV: test
  PORT: ${{ secrets.PORT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TEST_DB_URI: ${{ secrets.TEST_DB_URI }}

jobs:
  lint_and_test:
    name: 'Lint and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 'Lint'
        run: |
          npm install --prefix ./packages/backend
          npm run lint --prefix ./packages/backend && npm run test --prefix ./packages/backend
          npm install --prefix ./packages/frontend
          npm run lint --prefix ./packages/frontend

  notify:
    if: ${{ always() }}
    name: Notify about pull request
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Everything succeeded
        if: ${{ needs.lint_and_test.result == 'success' }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: New pull request, (lint and test passed)
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Something failed
        if: ${{ needs.lint_and_test.result == 'failure' }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: New pull request, (some checks didn't pass)
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
