name: Pull request workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  NODE_ENV: test
  PORT: ${{ secrets.PORT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TEST_DB_URI: ${{ secrets.TEST_DB_URI }}

jobs:
  lint:
    name: 'Lint files'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: 'Lint'
        run: pnpm lint

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: 'Run tests'
        run: pnpm test

  notify:
    if: ${{ always() }}
    name: Notify about pull request
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Everything succeeded
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: New pull request, (lint and test passed)
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Something failed
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: New pull request, (some checks didn't pass)
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
