name: Deployment workflow

on:
  push:
    branches:
      - deployment-shenaniganz

env:
  NODE_ENV: test
  PORT: ${{ secrets.PORT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy_backend:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./packages/backend/Dockerfile
          push: true
          tags: ollivarila/postbuddy-api:latest
      - name: Notify Azure about deployment
        run: curl -X POST ${{ secrets.AZURE_DEPLOYMENT_HOOK }} > /dev/null
